# Generated by Django 4.2.11 on 2024-05-01 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Daystarapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminemail', models.CharField(blank=True, max_length=100, null=True)),
                ('adminname', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('adminphone', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Babiesreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('babyname', models.CharField(blank=True, max_length=100, null=True)),
                ('babyage', models.IntegerField(blank=True, default=0, null=True)),
                ('babygender', models.CharField(blank=True, max_length=100, null=True)),
                ('babyloc', models.CharField(blank=True, max_length=100, null=True)),
                ('babyparent', models.CharField(blank=True, max_length=100, null=True)),
                ('babyno', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dollstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barbiedolls', models.IntegerField(blank=True, null=True)),
                ('teddybears', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk', models.IntegerField(blank=True, null=True)),
                ('diapers', models.IntegerField(blank=True, null=True)),
                ('fruits', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitterreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sittername', models.CharField(blank=True, max_length=100, null=True)),
                ('sitterbirth', models.DateField(blank=True, null=True)),
                ('sittergender', models.CharField(blank=True, max_length=100, null=True)),
                ('sitterloc', models.CharField(blank=True, max_length=100, null=True)),
                ('sitterNIN', models.CharField(blank=True, max_length=30, null=True)),
                ('sitterno', models.IntegerField(blank=True, null=True)),
                ('sitterkin', models.CharField(blank=True, max_length=100, null=True)),
                ('sitterreco', models.CharField(blank=True, max_length=100, null=True)),
                ('sitterreligion', models.CharField(blank=True, max_length=100, null=True)),
                ('sittereduc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picker', models.CharField(blank=True, max_length=100, null=True)),
                ('timein', models.DateTimeField(blank=True, null=True)),
                ('babypay', models.CharField(blank=True, default='UGX', max_length=10, null=True)),
                ('periodstay', models.CharField(blank=True, max_length=10, null=True)),
                ('babydrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Daystarapp.babiesreg')),
            ],
        ),
        migrations.CreateModel(
            name='Timeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout', models.DateTimeField(blank=True, null=True)),
                ('dropper', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('babypick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Daystarapp.timein')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=21, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('sell_to', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Daystarapp.dollstall')),
            ],
        ),
        migrations.CreateModel(
            name='Adminlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminpassw', models.CharField(blank=True, max_length=100, null=True)),
                ('adminnamee', models.CharField(blank=True, max_length=100, null=True)),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Daystarapp.adminreg')),
            ],
        ),
    ]
