# Generated by Django 4.2.11 on 2024-05-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daystarapp', '0003_assignbaby_rename_barbiedolls_dollstall_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='datesale',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
