# Generated by Django 4.2.11 on 2024-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daystarapp', '0004_sales_datesale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignbaby',
            name='babyassign',
        ),
        migrations.AddField(
            model_name='assignbaby',
            name='babyassign',
            field=models.ManyToManyField(to='Daystarapp.babiesreg'),
        ),
    ]
