# Generated by Django 4.2.11 on 2024-05-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Daystarapp', '0006_procuregive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignbaby',
            name='babyassign',
        ),
        migrations.AddField(
            model_name='assignbaby',
            name='babyassign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Daystarapp.babiesreg'),
            preserve_default=False,
        ),
    ]
