# Generated by Django 4.2.11 on 2024-05-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daystarapp', '0008_alter_babiesreg_babygender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babiesreg',
            name='periodstay',
            field=models.CharField(blank=True, choices=[('fullday', 'Full day'), ('halfday', 'Half day'), ('monthly', 'Monthly')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sitterreg',
            name='sittergender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True),
        ),
    ]
