# Generated by Django 4.2.11 on 2024-05-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daystarapp', '0009_alter_babiesreg_periodstay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babiesreg',
            name='babyname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
