# Generated by Django 4.2.11 on 2024-05-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Daystarapp', '0012_rename_babyassign_assignbaby_baby_being_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogin',
            name='login',
        ),
    ]
