# Generated by Django 4.2.11 on 2024-05-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Daystarapp', '0013_remove_adminlogin_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminlogin',
            old_name='adminnamee',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='adminlogin',
            old_name='adminpassw',
            new_name='username',
        ),
    ]
