# Generated by Django 4.2.11 on 2024-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daystarapp', '0014_rename_adminnamee_adminlogin_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babiesreg',
            name='babyage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
