# Generated by Django 4.2.11 on 2024-05-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Daystarapp', '0015_alter_babiesreg_babyage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='item',
            new_name='doll_item',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='price',
            new_name='total_price',
        ),
    ]
