# Generated by Django 4.2.11 on 2024-05-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Daystarapp', '0016_rename_item_sales_doll_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procuregive',
            old_name='procurequantity',
            new_name='amount',
        ),
    ]
