# Generated by Django 4.2.11 on 2024-05-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Daystarapp', '0017_rename_procurequantity_procuregive_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='sell_to',
            new_name='sell_to_baby',
        ),
    ]
